services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /var/certbot/www:/var/www/certbot:rw
    entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"'
    depends_on:
      - nginx

  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/usr/share/nginx/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django

  django:
    build: ./backend
    command: gunicorn lifelocker.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - ./backend:/usr/src/app
      - .env:/usr/src/.env
      - media_volume:/usr/src/media
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: lifelocker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume:
